name: Routine Checks

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  schedule:
    - cron: "0 0 * * *"

jobs:
  Test:
    name: Test

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Install dependencies
        run: pdm install --frozen-lock
      - name: Run tests
        run: pdm test
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snapshot_report
          path: snapshot_report.html
